# Generated by Django 3.2.5 on 2021-07-31 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Greeting",
        ),
    ]
